name: SAM Build/Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'sam.template.yaml'
      - 'src/main/**'
      - 'build.gradle'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Set Up Python
        uses: actions/setup-python@v2
      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v1
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Run SAM Build
        run: sam build -t sam.template.yaml

      - name: Run SAM Deploy
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --no-confirm-changeset  \
            --no-fail-on-empty-changeset  \
            --stack-name simple-java-lambda  \
            --s3-bucket ${{ secrets.AWS_S3_BUCKET }}  \
            --capabilities CAPABILITY_IAM  CAPABILITY_NAMED_IAM \
            --region ${{ secrets.AWS_REGION }}